import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthProvider from "./utils/SessionProvider";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <div className='mx-auto max-w-5xl text-2xl gap-2 mb-10'>
          <Navbar/>
        {children}
        </div>
        </AuthProvider>       
      </body>
    </html>
  );
}
